FROM osrf/ros:kinetic-desktop-full

#(Ubuntu 16.04: xenial, Ubuntu 14.04: trusty, Ubuntu 18.04: bionic)
ENV UBUNTU_VERSION=xenial

ENV ROS_VERSION=kinetic
# Set apt mirror to ucmirror and install extra packages
RUN apt-get update && \
    apt-get install -y \
    "ros-$ROS_VERSION-tf2-*" \
    "ros-$ROS_VERSION-camera-info-manager*" \
    && rm -rf /var/lib/apt/lists/*

# Sourcing this before .bashrc runs breaks ROS completions
RUN echo "\nsource /opt/ros/kinetic/setup.bash" >> $HOME/.bashrc
